### ISSUE TITLE
верстка гавно, афтар мудак

### ISSUE THREAD

**Issue by lenyaz** [Glebasher123/HTML-Labs#1]
[https://github.com/Glebasher123/HTML-Labs/blob/master/Lab4/Zadanie2_1.html]()
[https://github.com/Glebasher123/HTML-Labs/blob/master/Lab4/Zadanie2_2.html]()
<strong class="selflink"><b><font size="5"><i>Так&nbsp;&nbsp;&nbsp;&nbsp;</i></font> верстают <font size="6" color="lime"></font></b><font size="6" color="lime"><u>&nbsp;&nbsp;&nbsp;&nbsp;только</u><b></b></font><b>  </b><i><font size="7" color="blue">&nbsp;&nbsp;&nbsp;&nbsp;мудаки</font></i></strong>

**Comment by Glebasher123** [comment]
отсоси братик

**Comment by lenyaz** [comment]
ладно прості епта
